/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChatRoom = IDL.Record({
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'isVIP' : IDL.Bool,
  'roomId' : IDL.Nat,
});
export const Badge = IDL.Variant({
  'vip' : IDL.Null,
  'admin' : IDL.Null,
  'highScore' : IDL.Null,
  'founder' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'xp' : IDL.Nat,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'badges' : IDL.Vec(Badge),
  'role' : UserRole,
  'level' : IDL.Nat,
  'avatarUrl' : IDL.Text,
  'isBanned' : IDL.Bool,
  'isVIP' : IDL.Bool,
});
export const Timestamp = IDL.Int;
export const PrivateMessage = IDL.Record({
  'content' : IDL.Text,
  'messageId' : IDL.Nat,
  'sender' : IDL.Principal,
  'timestamp' : Timestamp,
  'receiver' : IDL.Principal,
});
export const GameId = IDL.Variant({
  'shooting' : IDL.Null,
  'quiz' : IDL.Null,
  'racing' : IDL.Null,
});
export const LeaderboardEntry = IDL.Record({
  'username' : IDL.Text,
  'userId' : IDL.Principal,
  'gameId' : GameId,
  'score' : IDL.Nat,
  'timestamp' : Timestamp,
});
export const PlatformStats = IDL.Record({
  'totalMessages' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'topPlayers' : IDL.Vec(LeaderboardEntry),
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'messageId' : IDL.Nat,
  'sender' : IDL.Principal,
  'timestamp' : Timestamp,
  'senderName' : IDL.Text,
  'roomId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addXp' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignAdminRole' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignVIP' : IDL.Func([IDL.Principal], [], []),
  'banUser' : IDL.Func([IDL.Principal], [], []),
  'createRoom' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Nat], []),
  'deleteRoom' : IDL.Func([IDL.Nat], [], []),
  'generateStory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
  'generateTitles' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getAllRooms' : IDL.Func([], [IDL.Vec(ChatRoom)], ['query']),
  'getAllUsersByUsername' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PrivateMessage)],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func([GameId], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getRecentMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'resetLeaderboard' : IDL.Func([GameId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendPrivateMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'setOwner' : IDL.Func([], [], []),
  'submitScore' : IDL.Func([GameId, IDL.Nat], [], []),
  'unbanUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChatRoom = IDL.Record({
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'isVIP' : IDL.Bool,
    'roomId' : IDL.Nat,
  });
  const Badge = IDL.Variant({
    'vip' : IDL.Null,
    'admin' : IDL.Null,
    'highScore' : IDL.Null,
    'founder' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'xp' : IDL.Nat,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'badges' : IDL.Vec(Badge),
    'role' : UserRole,
    'level' : IDL.Nat,
    'avatarUrl' : IDL.Text,
    'isBanned' : IDL.Bool,
    'isVIP' : IDL.Bool,
  });
  const Timestamp = IDL.Int;
  const PrivateMessage = IDL.Record({
    'content' : IDL.Text,
    'messageId' : IDL.Nat,
    'sender' : IDL.Principal,
    'timestamp' : Timestamp,
    'receiver' : IDL.Principal,
  });
  const GameId = IDL.Variant({
    'shooting' : IDL.Null,
    'quiz' : IDL.Null,
    'racing' : IDL.Null,
  });
  const LeaderboardEntry = IDL.Record({
    'username' : IDL.Text,
    'userId' : IDL.Principal,
    'gameId' : GameId,
    'score' : IDL.Nat,
    'timestamp' : Timestamp,
  });
  const PlatformStats = IDL.Record({
    'totalMessages' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'topPlayers' : IDL.Vec(LeaderboardEntry),
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'messageId' : IDL.Nat,
    'sender' : IDL.Principal,
    'timestamp' : Timestamp,
    'senderName' : IDL.Text,
    'roomId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addXp' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignAdminRole' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignVIP' : IDL.Func([IDL.Principal], [], []),
    'banUser' : IDL.Func([IDL.Principal], [], []),
    'createRoom' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Nat], []),
    'deleteRoom' : IDL.Func([IDL.Nat], [], []),
    'generateStory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
    'generateTitles' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getAllRooms' : IDL.Func([], [IDL.Vec(ChatRoom)], ['query']),
    'getAllUsersByUsername' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PrivateMessage)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [GameId],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getRecentMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'resetLeaderboard' : IDL.Func([GameId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendPrivateMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'setOwner' : IDL.Func([], [], []),
    'submitScore' : IDL.Func([GameId, IDL.Nat], [], []),
    'unbanUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };