/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Badge = { 'vip' : null } |
  { 'admin' : null } |
  { 'highScore' : null } |
  { 'founder' : null };
export interface ChatMessage {
  'content' : string,
  'messageId' : bigint,
  'sender' : Principal,
  'timestamp' : Timestamp,
  'senderName' : string,
  'roomId' : bigint,
}
export interface ChatRoom {
  'name' : string,
  'createdBy' : Principal,
  'description' : string,
  'isVIP' : boolean,
  'roomId' : bigint,
}
export type GameId = { 'shooting' : null } |
  { 'quiz' : null } |
  { 'racing' : null };
export interface LeaderboardEntry {
  'username' : string,
  'userId' : Principal,
  'gameId' : GameId,
  'score' : bigint,
  'timestamp' : Timestamp,
}
export interface PlatformStats {
  'totalMessages' : bigint,
  'totalUsers' : bigint,
  'topPlayers' : Array<LeaderboardEntry>,
}
export interface PrivateMessage {
  'content' : string,
  'messageId' : bigint,
  'sender' : Principal,
  'timestamp' : Timestamp,
  'receiver' : Principal,
}
export type Timestamp = bigint;
export interface UserProfile {
  'xp' : bigint,
  'bio' : string,
  'username' : string,
  'badges' : Array<Badge>,
  'role' : UserRole,
  'level' : bigint,
  'avatarUrl' : string,
  'isBanned' : boolean,
  'isVIP' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addXp' : ActorMethod<[Principal, bigint], undefined>,
  'assignAdminRole' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignVIP' : ActorMethod<[Principal], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  'createRoom' : ActorMethod<[string, string, boolean], bigint>,
  'deleteRoom' : ActorMethod<[bigint], undefined>,
  'generateStory' : ActorMethod<[string, string], string>,
  'generateTitles' : ActorMethod<[string], Array<string>>,
  'getAllRooms' : ActorMethod<[], Array<ChatRoom>>,
  'getAllUsersByUsername' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[Principal], Array<PrivateMessage>>,
  'getLeaderboard' : ActorMethod<[GameId], Array<LeaderboardEntry>>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getRecentMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postMessage' : ActorMethod<[bigint, string], undefined>,
  'resetLeaderboard' : ActorMethod<[GameId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendPrivateMessage' : ActorMethod<[Principal, string], undefined>,
  'setOwner' : ActorMethod<[], undefined>,
  'submitScore' : ActorMethod<[GameId, bigint], undefined>,
  'unbanUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];